baseURL = 'https://blog.huyixi.com/'
title = "huyixi's Blog"
theme = 'plain'
description = "A blog by developer and designer huyixi, covering Technology, Design, Life, and Music."

[languages]
[languages.en]
languageName = 'English'
weight = 1

[languages.zh]
languageName = '简体中文'
weight = 2

[permalinks]
post = "/:title/"

[markup]
[markup.highlight]
style = "github"

[menu]
[[menu.main]]
identifier = "home"
name = "site.home"
url = "/"
weight = 1

[[menu.main]]
identifier = "mail"
name = "site.mail"
url = "mailto:hi@huyixi.com"
weight = 2

[[menu.main]]
identifier = "weekly"
name = "site.weekly"
url = "https://weekly.huyixi.com"
weight = 3

[[menu.main]]
identifier = "RSS"
name = "site.RSS"
url = "/index.xml"
weight = 4

[[menu.main]]
identifier = "about"
name = "site.about"
url = "/about"
weight = 5
