baseURL = 'https://blog.huyixi.com/'
languageCode = 'en'
title = "huyixi's Blog"
theme = 'plain'
description = "A blog by developer and designer huyixi, covering Technology, Design, Life, and Music."

[languages]
[languages.en]
baseURL = 'https://en.blog.huyixi.com/'
languageName = 'English'
weight = 1

[languages.zh]
baseURL = 'https://zh.blog.huyixi.com/'
languageName = '简体中文'
weight = 2

[permalinks]
post = "/:title/"

[markup]
[markup.highlight]
style = "github"
