baseURL = 'https://blog.huyixi.com/'
title = "huyixi's Blog"
theme = 'plain'
description = "A blog by developer and designer huyixi, covering Technology, Design, Life, and Music."

[permalinks]
post = "/:title/"

[markup]
[markup.highlight]
style = "github"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "mail"
name = "Mail"
url = "mailto:hi@huyixi.com"
weight = 2

[[menu.main]]
identifier = "weekly"
name = "Weekly"
url = "https://weekly.huyixi.com"
weight = 3

[[menu.main]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"
weight = 4

[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.en.menus]
[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "mail"
name = "Mail"
url = "mailto:hi@huyixi.com"
weight = 2

[[languages.en.menu.main]]
identifier = "weekly"
name = "Weekly"
url = "https://weekly.huyixi.com"
weight = 3

[[languages.en.menu.main]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"
weight = 4

[[languages.en.menu.main]]
name = "About"
url = "/about"
weight = 5

[languages.zh]
languageName = "简体中文"
weight = 2
[languages.zh.menus]

[[languages.zh.menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[languages.zh.menu.main]]
identifier = "mail"
name = "邮件"
url = "mailto:hi@huyixi.com"
weight = 2

[[languages.zh.menu.main]]
identifier = "weekly"
name = "周报"
url = "https://weekly.huyixi.com"
weight = 3

[[languages.zh.menu.main]]
identifier = "RSS"
name = "RSS订阅"
url = "/index.xml"
weight = 4

[[languages.zh.menu.main]]
name = "About"
url = "/about/"
weight = 5
