name = 'plain'
version = '1.0.0'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'

homepage = 'https://huyixi.com'

demosite = 'https://blog.huyixi.com'

tags = ['blog', 'light', 'mini']
features = ['some', 'awesome', 'features']

[author]
name = 'huyixi'
homepage = 'https://huyixi.com'
